Config.BeerCrafting = {
    all = { -- Recipes in this category can be accessed by AL>L jobs
        --["pintglass"] = {
        --    {
        --        free = false,
        --        items = {
        --            {
        --                item = "beer",
        --                amount = 2,
        --                remove = true
        --            }
        --        },
        --        result = {
        --            item = "water_bottle",
        --            amount = 1
        --        },
        --        duration = 5000,
        --        dict = "anim@amb@business@meth@meth_monitoring_no_work@",
        --        clip = "so_board_with_cleaning_lazycook"
        --    }
        --}
    },
    vanilla = { -- Here is job-specific crafting
        --["pintglass"] = {
        --    {
        --        free = false,
        --        items = {
        --            {
        --                item = "beer",
        --                amount = 2,
        --                remove = true
        --            }
        --        },
        --        result = {
        --            item = "water_bottle",
        --            amount = 1
        --        },
        --        duration = 5000,
        --        dict = "anim@amb@business@meth@meth_monitoring_no_work@",
        --        clip = "so_board_with_cleaning_lazycook"
        --    }
        --}
    },
    --yellowjack = {
    --    ["pintglass"] = {{
    --        free = false,
    --        items = {{
    --            item = "pintglass",
    --            amount = 1,
    --            remove = true
    --        }},
    --        result = {
    --            item = "darkbeer",
    --            amount = 1
    --        },
    --        duration = 5000,
    --        dict = "anim@amb@business@meth@meth_monitoring_no_work@",
    --        clip = "so_board_with_cleaning_lazycook"
    --    }}
    --}
}