Config = Config or {}
Config.Ped = {
    {
        type = "fivem-appearance",
        coords = vector4(-318.01, -2718.62, 6.55, 308.93),
        hash = `mp_m_freemode_01`,
        tattoos = '[{"Count":1,"collection":"mpstunt_overlays","nameHash":"MP_MP_Stunt_tat_004_F"},{"Count":1,"collection":"mpheist3_overlays","nameHash":"mpHeist3_Tat_006_F"},{"Count":1,"collection":"mpheist3_overlays","nameHash":"mpHeist3_Tat_010_F"},{"Count":1,"collection":"mpheist3_overlays","nameHash":"mpHeist3_Tat_022_F"},{"Count":1,"collection":"mpvinewood_overlays","nameHash":"MP_Vinewood_Tat_019_F"},{"Count":1,"collection":"mpchristmas2017_overlays","nameHash":"MP_Christmas2017_Tattoo_006_F"},{"Count":1,"collection":"mpgunrunning_overlays","nameHash":"MP_Gunrunning_Tattoo_010_F"},{"Count":1,"collection":"mpgunrunning_overlays","nameHash":"MP_Gunrunning_Tattoo_012_F"},{"Count":1,"collection":"mpsmuggler_overlays","nameHash":"MP_Smuggler_Tattoo_003_F"},{"Count":1,"collection":"mpbusiness_overlays","nameHash":"MP_Buis_F_Back_001"},{"Count":1,"collection":"mplowrider2_overlays","nameHash":"MP_LR_Tat_000_F"},{"Count":1,"collection":"mpbiker_overlays","nameHash":"MP_MP_Biker_Tat_051_F"},{"Count":1,"collection":"mpsmuggler_overlays","nameHash":"MP_Smuggler_Tattoo_012_F"},{"Count":1,"collection":"mpheist3_overlays","nameHash":"mpHeist3_Tat_001_F"},{"Count":1,"collection":"mpheist3_overlays","nameHash":"mpHeist3_Tat_005_F"},{"Count":1,"collection":"mpheist3_overlays","nameHash":"mpHeist3_Tat_021_F"}]',
        data = '{"eyeColor":0,"model":"mp_m_freemode_01","headBlend":{"skinMix":0,"shapeSecond":0,"shapeFirst":2,"shapeMix":0,"skinFirst":4,"skinSecond":0},"faceFeatures":{"cheeksBoneHigh":0,"noseBoneHigh":0,"jawBoneBackSize":0,"nosePeakSize":0,"noseBoneTwist":0,"noseWidth":0,"cheeksWidth":0,"chinBoneSize":0,"chinBoneLowering":0,"lipsThickness":0,"jawBoneWidth":0,"nosePeakHigh":0,"cheeksBoneWidth":0,"eyesOpening":0,"chinBoneLenght":0,"chinHole":0,"neckThickness":0,"nosePeakLowering":0,"eyeBrownForward":0,"eyeBrownHigh":0},"headOverlays":{"lipstick":{"style":0,"opacity":0,"color":0},"sunDamage":{"style":0,"opacity":0,"color":0},"eyebrows":{"style":30,"opacity":1,"color":0},"moleAndFreckles":{"style":0,"opacity":0,"color":0},"blush":{"style":0,"opacity":0,"color":0},"chestHair":{"style":0,"opacity":0,"color":0},"blemishes":{"style":0,"opacity":0,"color":0},"bodyBlemishes":{"style":0,"opacity":0,"color":0},"makeUp":{"style":0,"opacity":0,"color":0},"complexion":{"style":0,"opacity":0,"color":0},"ageing":{"style":0,"opacity":0,"color":0},"beard":{"style":0,"opacity":0.8,"color":0}},"hair":{"style":12,"highlight":0,"color":29},"components":[{"drawable":0,"component_id":0,"texture":0},{"drawable":51,"component_id":1,"texture":1},{"drawable":12,"component_id":2,"texture":0},{"drawable":224,"component_id":3,"texture":0},{"drawable":24,"component_id":4,"texture":0},{"drawable":0,"component_id":5,"texture":0},{"drawable":6,"component_id":6,"texture":0},{"drawable":0,"component_id":7,"texture":0},{"drawable":15,"component_id":8,"texture":0},{"drawable":0,"component_id":9,"texture":0},{"drawable":0,"component_id":10,"texture":0},{"drawable":531,"component_id":11,"texture":0}],"props":[{"drawable":-1,"prop_id":0,"texture":0},{"drawable":25,"prop_id":1,"texture":4},{"drawable":-1,"prop_id":2,"texture":-1},{"drawable":-1,"prop_id":6,"texture":-1},{"drawable":-1,"prop_id":7,"texture":-1}]}'
    },
}